using System.ComponentModel;

namespace SourceCode.Vista
{
    partial class UserCtrlAdmin
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.title = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.txtID = new System.Windows.Forms.TextBox();
            this.txtPwd = new System.Windows.Forms.TextBox();
            this.txtName = new System.Windows.Forms.TextBox();
            this.txtDui = new System.Windows.Forms.TextBox();
            this.txtSurn = new System.Windows.Forms.TextBox();
            this.cmbD = new System.Windows.Forms.ComboBox();
            this.btnAdd = new System.Windows.Forms.Button();
            this.title2 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.cmbId = new System.Windows.Forms.ComboBox();
            this.btnDel = new System.Windows.Forms.Button();
            this.dateTimePicker1 = new System.Windows.Forms.DateTimePicker();
            this.btnClear = new System.Windows.Forms.Button();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.titlebuild = new System.Windows.Forms.Label();
            this.dataRegist = new System.Windows.Forms.DataGridView();
            this.titleReg = new System.Windows.Forms.Label();
            this.titleTop = new System.Windows.Forms.Label();
            this.dataBuilding = new System.Windows.Forms.DataGridView();
            this.lblfreq = new System.Windows.Forms.Label();
            this.lvlTop = new System.Windows.Forms.Label();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.lblMaxTemps = new System.Windows.Forms.Label();
            this.lblOldies = new System.Windows.Forms.Label();
            this.btnReturn = new System.Windows.Forms.Button();
            this.lblUser = new System.Windows.Forms.Label();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.dataGridView2 = new System.Windows.Forms.DataGridView();
            this.tableLayoutPanel1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dataRegist)).BeginInit();
            ((System.ComponentModel.ISupportInitialize) (this.dataBuilding)).BeginInit();
            this.tabPage3.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dataGridView1)).BeginInit();
            this.tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize) (this.dataGridView2)).BeginInit();
            this.SuspendLayout();
            this.tableLayoutPanel1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 460F));
            this.tableLayoutPanel1.Controls.Add(this.tabControl1, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.btnReturn, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.lblUser, 1, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.007576F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 92.99242F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(670, 528);
            this.tableLayoutPanel1.TabIndex = 0;
            this.tableLayoutPanel1.SetColumnSpan(this.tabControl1, 2);
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(3, 40);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(664, 485);
            this.tabControl1.TabIndex = 0;
            this.tabPage1.Controls.Add(this.tableLayoutPanel2);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(656, 459);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tableLayoutPanel2.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tableLayoutPanel2.ColumnCount = 6;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.938272F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19.44444F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 27.31482F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18.20988F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25.15432F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.938272F));
            this.tableLayoutPanel2.Controls.Add(this.title, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.label1, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.label2, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.label3, 1, 3);
            this.tableLayoutPanel2.Controls.Add(this.label6, 3, 1);
            this.tableLayoutPanel2.Controls.Add(this.label7, 3, 2);
            this.tableLayoutPanel2.Controls.Add(this.label8, 3, 3);
            this.tableLayoutPanel2.Controls.Add(this.label9, 1, 4);
            this.tableLayoutPanel2.Controls.Add(this.txtID, 2, 1);
            this.tableLayoutPanel2.Controls.Add(this.txtPwd, 4, 1);
            this.tableLayoutPanel2.Controls.Add(this.txtName, 2, 2);
            this.tableLayoutPanel2.Controls.Add(this.txtDui, 2, 3);
            this.tableLayoutPanel2.Controls.Add(this.txtSurn, 4, 2);
            this.tableLayoutPanel2.Controls.Add(this.cmbD, 2, 4);
            this.tableLayoutPanel2.Controls.Add(this.btnAdd, 4, 4);
            this.tableLayoutPanel2.Controls.Add(this.title2, 1, 5);
            this.tableLayoutPanel2.Controls.Add(this.label11, 1, 6);
            this.tableLayoutPanel2.Controls.Add(this.cmbId, 2, 6);
            this.tableLayoutPanel2.Controls.Add(this.btnDel, 4, 6);
            this.tableLayoutPanel2.Controls.Add(this.dateTimePicker1, 4, 3);
            this.tableLayoutPanel2.Controls.Add(this.btnClear, 3, 4);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 8;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(650, 453);
            this.tableLayoutPanel2.TabIndex = 0;
            this.tableLayoutPanel2.SetColumnSpan(this.title, 4);
            this.title.Dock = System.Windows.Forms.DockStyle.Fill;
            this.title.Location = new System.Drawing.Point(35, 0);
            this.title.Name = "title";
            this.title.Size = new System.Drawing.Size(578, 56);
            this.title.TabIndex = 0;
            this.title.Text = "label1";
            this.title.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Location = new System.Drawing.Point(35, 56);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(120, 56);
            this.label1.TabIndex = 1;
            this.label1.Tag = "add";
            this.label1.Text = "idUsuario:";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label2.Location = new System.Drawing.Point(35, 112);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(120, 56);
            this.label2.TabIndex = 1;
            this.label2.Tag = "add";
            this.label2.Text = "Nombre:";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label3.Location = new System.Drawing.Point(35, 168);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(120, 56);
            this.label3.TabIndex = 1;
            this.label3.Tag = "add";
            this.label3.Text = "DUI:";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label6.Location = new System.Drawing.Point(338, 56);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(112, 56);
            this.label6.TabIndex = 1;
            this.label6.Tag = "add";
            this.label6.Text = "Contraseña:";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label7.Location = new System.Drawing.Point(338, 112);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(112, 56);
            this.label7.TabIndex = 1;
            this.label7.Tag = "add";
            this.label7.Text = "Apellido:";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label8.Location = new System.Drawing.Point(338, 168);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(112, 56);
            this.label8.TabIndex = 1;
            this.label8.Tag = "add";
            this.label8.Text = "Fecha de nacimiento:";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label9.Location = new System.Drawing.Point(35, 224);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(120, 56);
            this.label9.TabIndex = 1;
            this.label9.Tag = "add";
            this.label9.Text = "Departamento:";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.txtID.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtID.Location = new System.Drawing.Point(161, 74);
            this.txtID.Name = "txtID";
            this.txtID.Size = new System.Drawing.Size(151, 20);
            this.txtID.TabIndex = 2;
            this.txtPwd.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtPwd.Location = new System.Drawing.Point(456, 74);
            this.txtPwd.Name = "txtPwd";
            this.txtPwd.Size = new System.Drawing.Size(151, 20);
            this.txtPwd.TabIndex = 2;
            this.txtName.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtName.Location = new System.Drawing.Point(161, 130);
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(151, 20);
            this.txtName.TabIndex = 2;
            this.txtDui.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtDui.Location = new System.Drawing.Point(161, 186);
            this.txtDui.Name = "txtDui";
            this.txtDui.Size = new System.Drawing.Size(151, 20);
            this.txtDui.TabIndex = 2;
            this.txtSurn.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.txtSurn.Location = new System.Drawing.Point(456, 130);
            this.txtSurn.Name = "txtSurn";
            this.txtSurn.Size = new System.Drawing.Size(151, 20);
            this.txtSurn.TabIndex = 2;
            this.cmbD.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.cmbD.FormattingEnabled = true;
            this.cmbD.Location = new System.Drawing.Point(161, 241);
            this.cmbD.Name = "cmbD";
            this.cmbD.Size = new System.Drawing.Size(151, 21);
            this.cmbD.TabIndex = 3;
            this.btnAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnAdd.Location = new System.Drawing.Point(456, 227);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(157, 50);
            this.btnAdd.TabIndex = 4;
            this.btnAdd.Text = "btnAdd";
            this.btnAdd.UseVisualStyleBackColor = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            this.tableLayoutPanel2.SetColumnSpan(this.title2, 4);
            this.title2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.title2.Font = new System.Drawing.Font("Consolas", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte) (0)));
            this.title2.Location = new System.Drawing.Point(35, 280);
            this.title2.Name = "title2";
            this.title2.Size = new System.Drawing.Size(578, 56);
            this.title2.TabIndex = 5;
            this.title2.Text = "title2";
            this.title2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label11.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label11.Location = new System.Drawing.Point(35, 336);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(120, 56);
            this.label11.TabIndex = 6;
            this.label11.Tag = "add";
            this.label11.Text = "idUsuario:";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cmbId.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.cmbId.FormattingEnabled = true;
            this.cmbId.Location = new System.Drawing.Point(161, 353);
            this.cmbId.Name = "cmbId";
            this.cmbId.Size = new System.Drawing.Size(151, 21);
            this.cmbId.TabIndex = 3;
            this.btnDel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnDel.Location = new System.Drawing.Point(456, 339);
            this.btnDel.Name = "btnDel";
            this.btnDel.Size = new System.Drawing.Size(157, 50);
            this.btnDel.TabIndex = 7;
            this.btnDel.Text = "btnDel";
            this.btnDel.UseVisualStyleBackColor = true;
            this.btnDel.Click += new System.EventHandler(this.btnDel_Click);
            this.dateTimePicker1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.dateTimePicker1.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dateTimePicker1.Location = new System.Drawing.Point(456, 186);
            this.dateTimePicker1.Name = "dateTimePicker1";
            this.dateTimePicker1.Size = new System.Drawing.Size(151, 20);
            this.dateTimePicker1.TabIndex = 8;
            this.btnClear.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.btnClear.Location = new System.Drawing.Point(338, 240);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new System.Drawing.Size(57, 23);
            this.btnClear.TabIndex = 9;
            this.btnClear.Text = "button1";
            this.btnClear.UseVisualStyleBackColor = true;
            this.btnClear.Click += new System.EventHandler(this.btnClear_Click);
            this.tabPage2.Controls.Add(this.tableLayoutPanel4);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(656, 459);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.tableLayoutPanel4.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tableLayoutPanel4.ColumnCount = 6;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.938272F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19.44444F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 27.31482F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5.692307F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 37.53846F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.938272F));
            this.tableLayoutPanel4.Controls.Add(this.titlebuild, 1, 0);
            this.tableLayoutPanel4.Controls.Add(this.dataRegist, 1, 5);
            this.tableLayoutPanel4.Controls.Add(this.titleReg, 1, 4);
            this.tableLayoutPanel4.Controls.Add(this.titleTop, 4, 0);
            this.tableLayoutPanel4.Controls.Add(this.dataBuilding, 1, 1);
            this.tableLayoutPanel4.Controls.Add(this.lblfreq, 4, 2);
            this.tableLayoutPanel4.Controls.Add(this.lvlTop, 4, 1);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 8;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(650, 453);
            this.tableLayoutPanel4.TabIndex = 4;
            this.tableLayoutPanel4.SetColumnSpan(this.titlebuild, 2);
            this.titlebuild.Dock = System.Windows.Forms.DockStyle.Fill;
            this.titlebuild.Location = new System.Drawing.Point(35, 0);
            this.titlebuild.Name = "titlebuild";
            this.titlebuild.Size = new System.Drawing.Size(297, 56);
            this.titlebuild.TabIndex = 0;
            this.titlebuild.Text = "label1";
            this.titlebuild.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.dataRegist.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.tableLayoutPanel4.SetColumnSpan(this.dataRegist, 4);
            this.dataRegist.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataRegist.Location = new System.Drawing.Point(35, 283);
            this.dataRegist.Name = "dataRegist";
            this.tableLayoutPanel4.SetRowSpan(this.dataRegist, 3);
            this.dataRegist.Size = new System.Drawing.Size(578, 167);
            this.dataRegist.TabIndex = 16;
            this.tableLayoutPanel4.SetColumnSpan(this.titleReg, 4);
            this.titleReg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.titleReg.Location = new System.Drawing.Point(35, 224);
            this.titleReg.Name = "titleReg";
            this.titleReg.Size = new System.Drawing.Size(578, 56);
            this.titleReg.TabIndex = 15;
            this.titleReg.Text = "label1";
            this.titleReg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.titleTop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.titleTop.Location = new System.Drawing.Point(375, 0);
            this.titleTop.Name = "titleTop";
            this.titleTop.Size = new System.Drawing.Size(238, 56);
            this.titleTop.TabIndex = 0;
            this.titleTop.Text = "label1";
            this.titleTop.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.dataBuilding.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.tableLayoutPanel4.SetColumnSpan(this.dataBuilding, 2);
            this.dataBuilding.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataBuilding.Location = new System.Drawing.Point(35, 59);
            this.dataBuilding.Name = "dataBuilding";
            this.tableLayoutPanel4.SetRowSpan(this.dataBuilding, 3);
            this.dataBuilding.Size = new System.Drawing.Size(297, 162);
            this.dataBuilding.TabIndex = 17;
            this.lblfreq.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblfreq.Location = new System.Drawing.Point(375, 112);
            this.lblfreq.Name = "lblfreq";
            this.lblfreq.Size = new System.Drawing.Size(238, 56);
            this.lblfreq.TabIndex = 18;
            this.lblfreq.Text = "label13";
            this.lblfreq.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lvlTop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lvlTop.Location = new System.Drawing.Point(375, 56);
            this.lvlTop.Name = "lvlTop";
            this.lvlTop.Size = new System.Drawing.Size(238, 56);
            this.lvlTop.TabIndex = 18;
            this.lvlTop.Text = "label13";
            this.lvlTop.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tabPage3.Controls.Add(this.tableLayoutPanel5);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(656, 459);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "tabPage3";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.tableLayoutPanel5.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tableLayoutPanel5.ColumnCount = 5;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.938272F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 43.72019F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.769475F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 46.58187F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel5.Controls.Add(this.dataGridView1, 1, 1);
            this.tableLayoutPanel5.Controls.Add(this.lblMaxTemps, 1, 0);
            this.tableLayoutPanel5.Controls.Add(this.lblOldies, 3, 0);
            this.tableLayoutPanel5.Controls.Add(this.dataGridView2, 3, 1);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 3;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.27358F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 83.72642F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(650, 453);
            this.tableLayoutPanel5.TabIndex = 4;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataGridView1.Location = new System.Drawing.Point(34, 72);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.Size = new System.Drawing.Size(269, 349);
            this.dataGridView1.TabIndex = 16;
            this.lblMaxTemps.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMaxTemps.Location = new System.Drawing.Point(34, 0);
            this.lblMaxTemps.Name = "lblMaxTemps";
            this.lblMaxTemps.Size = new System.Drawing.Size(269, 69);
            this.lblMaxTemps.TabIndex = 17;
            this.lblMaxTemps.Text = "lbltemp";
            this.lblMaxTemps.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblOldies.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblOldies.Location = new System.Drawing.Point(339, 0);
            this.lblOldies.Name = "lblOldies";
            this.lblOldies.Size = new System.Drawing.Size(287, 69);
            this.lblOldies.TabIndex = 17;
            this.lblOldies.Text = "lbltemp";
            this.lblOldies.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReturn.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnReturn.Location = new System.Drawing.Point(3, 3);
            this.btnReturn.Name = "btnReturn";
            this.btnReturn.Size = new System.Drawing.Size(172, 31);
            this.btnReturn.TabIndex = 1;
            this.btnReturn.Text = "button1";
            this.btnReturn.UseVisualStyleBackColor = true;
            this.btnReturn.Click += new System.EventHandler(this.btnReturn_Click);
            this.lblUser.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUser.Location = new System.Drawing.Point(213, 0);
            this.lblUser.Name = "lblUser";
            this.lblUser.Size = new System.Drawing.Size(454, 37);
            this.lblUser.TabIndex = 2;
            this.lblUser.Text = "label1";
            this.tableLayoutPanel3.ColumnCount = 6;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.923077F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 22.46154F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24.15385F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 22.92308F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20.30769F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.923077F));
            this.tableLayoutPanel3.Controls.Add(this.label4, 1, 0);
            this.tableLayoutPanel3.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(200, 100);
            this.tableLayoutPanel3.TabIndex = 0;
            this.tableLayoutPanel3.SetColumnSpan(this.label4, 4);
            this.label4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label4.Location = new System.Drawing.Point(12, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(172, 100);
            this.label4.TabIndex = 0;
            this.label4.Text = "label1";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.label5.Location = new System.Drawing.Point(12, 64);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(94, 32);
            this.label5.TabIndex = 1;
            this.label5.Text = "label1";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.dataGridView2.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataGridView2.Location = new System.Drawing.Point(339, 72);
            this.dataGridView2.Name = "dataGridView2";
            this.dataGridView2.Size = new System.Drawing.Size(287, 349);
            this.dataGridView2.TabIndex = 18;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tableLayoutPanel1);
            this.Name = "UserCtrlAdmin";
            this.Size = new System.Drawing.Size(670, 528);
            this.Load += new System.EventHandler(this.UserCtrlAdmin_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dataRegist)).EndInit();
            ((System.ComponentModel.ISupportInitialize) (this.dataBuilding)).EndInit();
            this.tabPage3.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dataGridView1)).EndInit();
            this.tableLayoutPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize) (this.dataGridView2)).EndInit();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Button btnClear;
        private System.Windows.Forms.Button btnDel;
        private System.Windows.Forms.Button btnReturn;
        private System.Windows.Forms.ComboBox cmbD;
        private System.Windows.Forms.ComboBox cmbId;
        private System.Windows.Forms.DataGridView dataBuilding;
        private System.Windows.Forms.DataGridView dataGridView1;
        private System.Windows.Forms.DataGridView dataGridView2;
        private System.Windows.Forms.DataGridView dataRegist;
        private System.Windows.Forms.DateTimePicker dateTimePicker1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label lblfreq;
        private System.Windows.Forms.Label lblMaxTemps;
        private System.Windows.Forms.Label lblOldies;
        private System.Windows.Forms.Label lblUser;
        private System.Windows.Forms.Label lvlTop;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.Label title;
        private System.Windows.Forms.Label title2;
        private System.Windows.Forms.Label titlebuild;
        private System.Windows.Forms.Label titleReg;
        private System.Windows.Forms.Label titleTop;
        private System.Windows.Forms.TextBox txtDui;
        private System.Windows.Forms.TextBox txtID;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TextBox txtPwd;
        private System.Windows.Forms.TextBox txtSurn;

        private System.Windows.Forms.Button button1;

        #endregion
    }
}